# pull official base image
FROM node:16.15-alpine

# add app
COPY . ./

RUN npm install --silent
RUN npm run build
RUN yarn global add serve

EXPOSE 3000

# start app
ENTRYPOINT ["serve", "-s", "build"]
