# pull official base image
FROM node:16.15-alpine

# add app
COPY src ./src
COPY public ./public

# install app dependencies
COPY package.json ./
COPY package-lock.json ./
RUN npm install --silent

EXPOSE 3000

# start app
ENTRYPOINT ["npm", "start"]
